### PR TITLE
Modification to use CoinMarketCap with API, RegExp, and some common Variables

### PR DESCRIPTION
**Pull request by thickconfusion**
Addresses #10, #5, and #9. Chiefly, each GET from the API needs to have the API provided in the header. PR adds variable location for you to place your API key to connect to CoinMarketCap instead of placing this in each section. Also updated URLs for CoinMarketCap's Pro API (not as a variable), and updated the regular expressions to pull the data correctly from the API as a variable. On second thought perhaps the URL should also be a variable but oh well.

### CODE REVIEW

**Comment by bkuhl** [comment]
This is awesome, thank you!  Would you mind updating the README with instructions for how to obtain an API key, and guiding people to update the .ini file?

**Comment by brainstormer3009** [comment]
Oh yeah! It's working. Thank you very much, guys!!!!!!

**Comment by bkuhl** [comment]
I'm gonna go ahead and merge this, since clearly it's helpful!  It'd be great if you were able to spend a few minutes to write up some documentation, or getting started steps for folks so they know how to get an API key.

**Comment by thickconfusion** [comment]
I'll spend some time making an update to the Readme and do another PR. May be a few days before I get around to it.

**Comment by brainstormer3009** [comment]
Getting an API-Key for FREE from Coinmarketcap
================================

1. go to https://pro.coinmarketcap.com/signup
2. sidn up and follow the instructions
3. in the Dashboard click on 'COPY KEY' on box with the stars '********_' 
4, Done! You've got the key!

I know, that's not the right place for a documantation ;)

**Comment by bkuhl** [comment]
Good enough, I've taken that and updated the Installation directions - https://github.com/bkuhl/cryptometer/blob/master/README.md#installation

**Pull request merged**
