### PR TITLE
Allow spaces or nothing, potentially a little safer than a ".*" fix

### PR DESCRIPTION
**Pull request by eltonlockhart**
Another choice for fixing the regex.

### CODE REVIEW

**Review by mschilmann — COMMENTED** [review]
Please remove your coinmarketcap API key from your pull request. (and best would be to generate a new one)

**Comment by eltonlockhart** [comment]
:| sigh

**Comment by eltonlockhart** [comment]
> Please remove your coinmarketcap API key from your pull request. (and best would be to generate a new one)

Thanks a bit of an oversight after a late tweak.

**Comment by just-rich** [comment]
[FIXED] NOT SHOWING CRYPTO PRICES. Was not showing any prices after "$"
Some type of 'RegEx' error
how was this regex error fixed?

[https://ibb.co/wQTzDyS](url)

 Open the script "Cryptometer-Medium"- click 'edit' then 'Find' and type in "RegEx"- the first result will have a line of code after RegEx= remove it and replace it with one of the following. Save, then hit 'Refresh' in the Rainmeter manager.

This fix worked; RegEx=(?siU)"price":\s*(\d*\.\d{0,2}?).*percent_change_1h":\s*([-+]?\d*\.\d{0,2}?).*percent_change_24h":\s*([-+]?\d*\.\d{0,2}?).*percent_change_7d":\s*([-+]?\d*\.\d{0,2}?)

This fix worked; RegEx=(?siU)"price".*(\d*\.\d{0,2}?).*"percent_change_1h".*([-+]?\d*\.\d{0,2}?).*"percent_change_24h".*([-+]?\d*\.\d{0,2}?).*"percent_change_7d".*([-+]?\d*\.\d{0,2}?)

Not sure what the actual difference is between the 2 from the original besides 1 fix has decimals replacing the colons. And the other replaces the colons with ":\s" - whatever that means and is supposed to? None the less both of them worked.

**Comment by eltonlockhart** [comment]
I have compared the github submitted configuration with my working config (regex below) and there are no differences other than the 4 decimal place change I added myself later.

`RegEx=(?siU)"price":\s*(\d*\.\d{0,4}?).*percent_change_1h":\s*([-+]?\d*\.\d{0,2}?).*percent_change_24h":\s*([-+]?\d*\.\d{0,2}?).*percent_change_7d":\s*([-+]?\d*\.\d{0,2}?)
`

**Comment by just-rich** [comment]
Yes I figured it out- thank you. I edited my post for anyone else that has the problem and doesn't realize to click on "Files changed" like myself.

**Comment by eltonlockhart** [comment]
Added a further tweak to resolve rejection of the default UserAgent value used by WebParser.

**Comment by bkuhl** [comment]
Great, thank you for following up on this.  Is this good to merge?

**Comment by eltonlockhart** [comment]
I'm not aware of any issues and I have been running my configuration for months now.

**Comment by bkuhl** [comment]
Awesome, thanks

**Pull request merged**
